export const languages = [
  { label: "Plain Text", value: "plaintext" },
  { label: "TypeScript", value: "typescript" },
  { label: "JavaScript", value: "javascript" },
  { label: "CSS", value: "css" },
  { label: "LESS", value: "less" },
  { label: "SCSS", value: "scss" },
  { label: "JSON", value: "json" },
  { label: "HTML", value: "html" },
  { label: "XML", value: "xml" },
  { label: "PHP", value: "php" },
  { label: "C#", value: "csharp" },
  { label: "C++", value: "cpp" },
  { label: "Razor", value: "razor" },
  { label: "Markdown", value: "markdown" },
  { label: "Diff", value: "diff" },
  { label: "Java", value: "java" },
  { label: "VB", value: "vb" },
  { label: "CoffeeScript", value: "coffeescript" },
  { label: "Handlebars", value: "handlebars" },
  { label: "Batch", value: "bat" },
  { label: "Pug", value: "pug" },
  { label: "F#", value: "fsharp" },
  { label: "Lua", value: "lua" },
  { label: "Powershell", value: "powershell" },
  { label: "Python", value: "python" },
  { label: "Ruby", value: "ruby" },
  { label: "SASS", value: "sass" },
  { label: "R", value: "r" },
  { label: "Objective-C", value: "objective-c" },
] as const;
